### ISSUE TITLE
Unable to specify which record to enable Cloudflare for

### ISSUE THREAD

**Issue by LiftedKilt** [danielpigott/cloudflare-cli#12]
Is there a way that I can specify a value for the record that I would like to enable cloudflare for?

For example - if I have two A records with the same name but different IPs, invoking `cfcli enablecf recordname` will activate it for both records. It ignores any value supplied. I have also tried `cfcli editrecord recordname --activate`, however that is not a valid option.

Any thoughts? I poked through the cfcli.js file myself to see if I could easily add it, but my javascript knowledge is depressingly poor.

**Comment by danielpigott** [comment]
I will be able to update it so you can specify the value you want to enable cf for, similar to the changes I made to remove record.  Will update this ticket once I have published the changes.

**Comment by danielpigott** [comment]
In the latest version (1.5.1) I have updated the enablecf command so you can apply it to records with particular values. e.g cfcli enablecf recordname recordvalue
