### ISSUE TITLE
Syntax for adding MX records?

### ISSUE THREAD

**Issue by LiftedKilt** [danielpigott/cloudflare-cli#13]
What is the syntax for MX records? Without specifying the priority, I get a 

`"No priority is present for a MX or SRV record." error.`

I can't seem to get it to accept the priority in any location in the command.

`cfcli addrecord -t MX domain.com mail.domain.com 100`

causes it to just ignore the priority and returns the same error.

Thanks

**Comment by danielpigott** [comment]
Hi @LiftedKilt  thanks for bringing this to my attention. I have added a new parameter -p in the latest version (1.5.1)  so you will now be able to set the priority when adding records.
