### ISSUE TITLE
How to get token?

### ISSUE THREAD

**Issue by nopret** [danielpigott/cloudflare-cli#14]
Could you please point at how to get a token?

**Comment by bAndie91** [comment]
You have to register at cloudflare.com [https://www.cloudflare.com/a/sign-up] to use Cloudflare's benefits.
Sign in and see your account's api token on page: https://www.cloudflare.com/a/account/my-account .
I wont put this info to project's docs, while it is trivial to have a Cloudflare account to manage Cloudflare settings.

**Comment by danielpigott** [comment]
Please see this cloudflare support article for instructions on getting your api key.
https://support.cloudflare.com/hc/en-us/articles/200167836-Where-do-I-find-my-CloudFlare-API-key-

**Comment by nopret** [comment]
The reason I asked is because I do have an API key but could not make it work with cfcli:
[Error: Invalid token or email]
So I wondered is there some kind of another token involved (!= API key), like access token after authorizing an app. 
Anyway, if API key is what I need and it's not working, any idea how to debug it further?

**Comment by nopium** [comment]
No problem, I figured it out.
