### ISSUE TITLE
Missing configuration options for SRV records

### ISSUE THREAD

**Issue by denderello** [danielpigott/cloudflare-cli#16]
Looks like the configuration options to create SRV records are not complete.

When I run:
```
cfcli addrecord -t SRV -p 1 _foo._tcp.your.domain SRV 1 12345 service.domain
```
The result is:
```
[Error: Invalid service value.]
```
This also happens with multiple variations of the arguments.

Looking at the [API docs for the `rec_new`](https://www.cloudflare.com/docs/client-api.html#s5.1) function I get the feeling that parameters like `service`, etc. have to passed separately when creating SRV records.

Maybe I am just using it wrong, but I was not able to find a way to create an SRV record. Any idea? :)

**Comment by danielpigott** [comment]
Thanks for the feedback, I have updated this in 1.6.0 so you can now create an SRV record as below, where the numbers are priority, weight and port respectively
cfcli addrecord -t SRV _foo._tcp.your.domain 1 1 12345 service.domain
