### ISSUE TITLE
Editting A record

### ISSUE THREAD

**Issue by xogium** [danielpigott/cloudflare-cli#18]
Hi,
When trying to edit the A record of my domain, even if I specify -t A in the command, and no matter where it is specified, before or after the 'editrecord' command, I get this:
Found 3 records that matched domain.tld. canceling edit. My record are as follow. 4 CNAMEs, 1 A record, 1 MX and 1 TXT. The command I'm trying to do is:
cfcli -t A editrecord domain.tld $(curl icanhazip.com)
or:
cfcli editrecord -t A domain.tld $(curl icanhazip.com)

Both commands gives the same result. Is there something I'm doing wrong ? Or is it a bug ?
Thanks :)

**Comment by danielpigott** [comment]
At present there isn't a way to edit a specific record. I will take a look at this and see if I can add it in.

**Comment by bfred-it** [comment]
It looks like you want to use it as a Dynamic DNS. This works for me:

```sh
cfcli edit local $(internal-ip)
```

- `local` is the subdomain name: `local.example.com`
- [`public-ip`](https://github.com/sindresorhus/public-ip
)

**Comment by danielpigott** [comment]
I think this should be OK now, going to close this ticket, let me know if it is still an issue

**Comment by xogium** [comment]
Hi,
sorry for not answering sooner, been busy :)

I updated to the most recent version of cloudflare-cli and am now facing a weird issue

If I do:

```
cfcli -t A edit domain.tld $(curl icanhazip.com)
updated A record...
```

Except, the record content is still the same.

```
cfcli -t A edit domain.tld 50.100.120.152
Error: No matching record found.
```

Any clue ?

I need to remove and to ad the record again to get it to work with the new ip. I cannot make a subdomain for the ip in question, this is the main tld.
