### ISSUE TITLE
Add support for setting TTL on records

### ISSUE THREAD

**Issue by eik3** [danielpigott/cloudflare-cli#2]
It would be great to be able to set the TTL when creating or updating records. The API supports it: https://www.cloudflare.com/docs/client-api.html#s5

**Comment by danielpigott** [comment]
Good idea, I'll look at adding it as a parameter for the next update

**Comment by danielpigott** [comment]
With version 1.1.0, I have added the ability to use the flag --ttl or -l to set the TTL on add or edit.  The listrecords command will now also include the TTL
