### ISSUE TITLE
API v1 is now deprecated and will be removed on November 9th, 2016. Need to move to v4.

### ISSUE THREAD

**Issue by gotts2swim** [danielpigott/cloudflare-cli#22]
The CloudFlare npm module you're using is an older version with API v1 which connects to the endpoint: [https://www.cloudflare.com/api_json.html](https://www.cloudflare.com/api_json.html)

As CloudFlare has deprecated the v1 API, we should move towards using the new v4 API.
The new endpoint for this is: [https://api.cloudflare.com/client/v4](https://api.cloudflare.com/client/v4)

As far as i know, the latest version of the CloudFlare npm module supports the v4 API.

**Comment by danielpigott** [comment]
Thanks, I am aware of the removal of the old API and that the newer version of the cloudflare module supports the new API.  Unfortunately the changes will require a bit of a rewrite as the cloudflare npm module was rewritten and is quite different.  I will be updating this in version 2 and will definitely get to it before November

**Comment by danielpigott** [comment]
cloudflare-cli v2 now uses the v4 api and is available on npm

**Comment by gotts2swim** [comment]
Awesome! Glad to hear it. I'll try it out.
