### ISSUE TITLE
supporting env variables

### ISSUE THREAD

**Issue by chanlvh** [danielpigott/cloudflare-cli#25]
storing those values in file is good, but perhaps some will prefer storing them in env variables instead. Shouldn't the command line look for those vals in env var too?

**Comment by danielpigott** [comment]
I'll take a look at adding this in for the next update

**Comment by jleclanche** [comment]
Would be nice to have support for CF_API_KEY and CF_API_EMAIL just like the official flarectl (https://github.com/cloudflare/cloudflare-go/tree/master/cmd/flarectl).

**Comment by danielpigott** [comment]
I have added support for the CF_API_KEY and CF_API_EMAIL environment variables in v2.30.0
