### ISSUE TITLE
[Feature Request] Support getting token from external command

### ISSUE THREAD

**Issue by xelxebar** [danielpigott/cloudflare-cli#26]
## Synopsis

For those of us who like to keep our home directory under version control, explicitly setting the `token` field in `cfcli.yml` forces us to not track that for unless we risk leaking the token. My preferred solution to this is allowing the token to be retrieved from an external command.

## Examples from Other Projects

Pianobar, for example, has a [`password_command`][3] setting for just this. Other solutions exist as well though. Mutt has a [`source`][1] command that can run commands from the output of an external command. That's pretty clunky, but offlineimap allows setting usernames and passwords with an external command with its [`remoteusereval` and `remotepasseval`][2] commands.

## Implementation Idea

I'm not that familiar with node.js, but from a quick search of th edocs it seems this could be implemented in a relatively straightforward manner using [`child_process.exec`][4].

[1]:http://www.mutt.org/doc/manual/#source
[2]:http://www.offlineimap.org/doc/use_cases.html#imap-using-name-translations
[3]:http://manpages.ubuntu.com/manpages/xenial/man1/pianobar.1.html
[4]:https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by danielpigott** [comment]
I have implemented loading credentials from environment variables in 2.30.0.  Hopefully this should allow you to implement a solution where you can load the credentials securely.
