### ISSUE TITLE
[Feature Idea] Output help when no command or options are given

### ISSUE THREAD

**Issue by xelxebar** [danielpigott/cloudflare-cli#27]
I personally find it more intuitive and in line with other cli tools to display the help output when no commands or options are given.

This confused me for a bit at first when `cfcli` alone on the command line gave no output and didn't even return an error code to the shell.

**Comment by danielpigott** [comment]
Seems like a good idea to me, I'll include it in the next update

**Comment by adenau** [comment]
+1 on this one. Also, error messages when nothings happens would be useful or an incorrect command is used would be useful. For example,

`cfcli delete test `

returns nothing.

**Comment by danielpigott** [comment]
This has been included in 2.1.0 which is now released
