### ISSUE TITLE
Purge multiple files at once.

### ISSUE THREAD

**Issue by geelen** [danielpigott/cloudflare-cli#29]
Looks like the API can take an array of up to 30 files to purge, but this line is passing things through as a single string: https://github.com/danielpigott/cloudflare-cli/blob/master/index.js#L370

I think could treat any args at the end of the file as a space-separated list of URLs:

```
cfcli purge http://example.com/ https://example.com/ http://example.com/help https://example.com/help
```

Would that work?

**Comment by danielpigott** [comment]
I should be able to make this change and include it in the next release

**Comment by danielpigott** [comment]
This has been added in 2.1.0 so supplying multiple urls will now work as in your example
```
cfcli purge http://example.com/ https://example.com/ http://example.com/help https://example.com/help
```
