### ISSUE TITLE
cannot `enablecf` on the "root" domain

### ISSUE THREAD

**Issue by SnakeO** [danielpigott/cloudflare-cli#30]
I have no problem enablecf / disablecf on the subdomain, like so:
`/usr/local/bin/cfcli -t A --domain mydomain.com enablecf www mydomain.com`

However, when I attempt the same thing on the root domain, like so:
` /usr/local/bin/cfcli -t A --domain mydomain.com enablecf mydomain.com 1.2.3.4`

I get this error:
`Error: 8 matching records found, unable to update`

And the output of `ls` (csv):
```
A,cpanel.mydomain.com,3.4.5.6,Auto,false
A,mydomain.com,1.2.3.4,Auto,true
CNAME,ftp.mydomain.com,mydomain.com,Auto,false
CNAME,mail.mydomain.com,mydomain.com,Auto,false
CNAME,www.mydomain.com,mydomain.com,Auto,true
MX,mydomain.com,alt1.aspmx.l.google.com,Auto,false
MX,mydomain.com,alt2.aspmx.l.google.com,Auto,false
MX,mydomain.com,alt3.aspmx.l.google.com,Auto,false
MX,mydomain.com,alt4.aspmx.l.google.com,Auto,false
MX,mydomain.com,aspmx.l.google.com,Auto,false
TXT,mydomain.com,google-site-verification=blah-BW5W9QiF0,Auto,false
TXT,mydomain.com,v=spf1 include:spf.protection.outlook.com ~all,Auto,false
```

halp?

**Comment by danielpigott** [comment]
I have fixed this issue in 2.1.0, so it will now correctly match the root domain
