### ISSUE TITLE
Cannot add MX record

### ISSUE THREAD

**Issue by azatuni** [danielpigott/cloudflare-cli#31]
Hello,

Cannot add MX record on cfcli version 2.0.3. Also same command is normal working on cfcli 1.5.2
<code>
cfcli -d example.com -t MX  addrecord example.com mail.example.com -p 1 -l 3600

Error: Response code 400 (Bad Request)
</code>

Thanks beforehand,
BR, Areg

**Comment by danielpigott** [comment]
I haven't been able to reproduce this error as yet.  Can you please check that it is still occurring?
With the next release I'm going to look at getting some more detail in the error messages, so hopefully that will give me a bit more to go on.
