### ISSUE TITLE
Error: Cannot set static values

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [danielpigott/cloudflare-cli#33]
Im trying to test the API with the following command: `cfcli -d mywebsite.com devmode on`

Im getting this output: `Error: Cannot set static values`

Im pretty sure my yaml config is correct, it is listing all the right zones when I run `cfcli zones`

**Comment by danielpigott** [comment]
Looks like the updated [cloudflare library](https://github.com/cloudflare/node-cloudflare) doesn't support this call yet (could have sworn it was working).  I'll take a look at making the required changes and putting in a pull request

**Comment by matthewjumpsoffbuildings** [comment]
@danielpigott any news on this?

**Comment by rockethouse** [comment]
+1 on this

**Comment by rockethouse** [comment]
@danielpigott Any updates on this?

**Comment by danielpigott** [comment]
Haven't had any time to work on this at the moment, will look at using a different api library (https://www.npmjs.com/package/cloudflare4) to make this call, which should mean I can get it fixed a bit quicker

**Comment by danielpigott** [comment]
I have updated the command to use the alternate library and it should work as expected now. (v2.2.0)
