### ISSUE TITLE
Create a zone

### ISSUE THREAD

**Issue by bogdanr** [danielpigott/cloudflare-cli#34]
The API [supports this operation](https://api.cloudflare.com/#zone-create-a-zone) and it would be nice to have this option because we could automate the process of adding a domain to CloudFlare completely.

**Comment by kevinrook** [comment]
would love this feature.

its great adding dns records to existing zones.
but i add many new domains everyday and its just this 1 step i have to still use the website for

**Comment by danielpigott** [comment]
Now that I have removed the dependencies on other cloudflare libraries this should be pretty straight forward to implement; I will include it in the next release

**Comment by wingZero21** [comment]
Any idea when this update is coming for the zone creation @danielpigott as I can see this being really useful for us!

**Comment by danielpigott** [comment]
I have added the zone-add command to version 3.1.0 which has now been released
