### ISSUE TITLE
Edit CNAME

### ISSUE THREAD

**Issue by scarbies** [danielpigott/cloudflare-cli#35]
How do I edit a CNAME record?
I home baked my own cloudflare shell script until I found this amazing repo. But I need to update CNAME for my DNS failover mechanism.

I've tried all possible combinations and none seem to work?

`# cfcli -t CNAME edit app b.domain.co.za`
`Error: No matching records found`

But `app.domain.co.za` does exist!

If this cannot be done then we need to update docs?

**Comment by danielpigott** [comment]
This looks like it should work, I'll take a look and see if I can see why this might be happening

**Comment by scarbies** [comment]
Thank you, let me know if you need any help or further details.

**Comment by PiWhy** [comment]
I have the same issue.

Is the "content" argument of the "edit" command used to find the existing record or is it the new content ?

Thanks

**Comment by danielpigott** [comment]
This should be fixed now in version 2.3.0. The command was incorrectly using the content value to try to search for the record. If you need to edit a particular record you can use the new --query (-q) parameter as in the example below:
```
cfcli -t CNAME edit app b.domain.co.za -q content:a.domain.co.za
```

This will change the app record with a content value of a.domain.co.za to now point to b.domain.co.za

**Comment by scarbies** [comment]
Wonderful thank you Daniel, I will give it a go. However I think you mean? 

`cfcli -t CNAME edit b.domain.co.za -q content:a.domain.co.za`

**Comment by danielpigott** [comment]
No problem. No I  meant that based on your original message
> cfcli -t CNAME edit app b.domain.co.za

app would be the CNAME and b.domain.co.za would be the value wish to set it to

adding -q content:a.domain.co.za will only affect records with that specific content value
