### ISSUE TITLE
cloudflare v1.1.1 contains security vulnerabilities

### ISSUE THREAD

**Issue by adubatl** [danielpigott/cloudflare-cli#37]
cloudflare 1.1.1 uses verymodel which uses an old version of joi containing the hoek vulnerability.

![screen shot 2018-05-16 at 9 20 07 am](https://user-images.githubusercontent.com/17996250/40119453-bddfe77a-58ea-11e8-99b1-c0b511b39b89.png)

Here is the vulnerability
https://nodesecurity.io/advisories/566

The newest version of cloudflare does not have this issue.

**Comment by danielpigott** [comment]
Thanks, I'll take a look, though I'm not sure how quick I'll be able to get this done as version 2.x of cloudflare seems to have undergone a bit of a rewrite

**Comment by danielpigott** [comment]
I have removed both the cloudflare and cloudflare4 dependencies with axios as part of v3.0.0.
