### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by kierenj** [danielpigott/cloudflare-cli#38]
Commands which fail:
`cfcli -a -t A add anything 1.2.3.4`
`cfcli ls`

Background:
The below happens on Windows if I don't have the environment variables set.
It happens on Linux (within docker image `node:10`) even if I do.

Exception:
```
(node:17) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at /usr/local/lib/node_modules/cloudflare-cli/index.js:170:52
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Continuing to investigate my side..

**Comment by kierenj** [comment]
Ok, specifying the config on the commandline seems to work in both cases.  Environment vars - not so much in the case of Linux

**Comment by danielpigott** [comment]
Thanks for the bug report Kieren. I have published a new version 3.1.1 with improved error handling, so you should get a more useful error message when you run the command

**Comment by danielpigott** [comment]
I'm using the environment variables in my CI builds (https://circleci.com/gh/danielpigott/cloudflare-cli) which is an Ubuntu container and that is picking them up, so I think there must only be certain circumstances where it isn't working

**Comment by danielpigott** [comment]
I'm going close this issue, as there isn't much I can do without more info. Please reopen if you have more info
