### ISSUE TITLE
Zones-Add Multipul accounts

### ISSUE THREAD

**Issue by kevinrook** [danielpigott/cloudflare-cli#40]
HI, just seen you have added zones-add great thanks.

how does this work with several accounts.

cfcli -u "account email" zone-add test.com

i have 10 CloudFlare accounts setup and an 11th account that has access to all 10 accounts using CF's members feature.

Kevin

**Comment by danielpigott** [comment]
Hi Kevin,
The tool doesn't currently support adding zones using an account with access to multiple accounts.
You can use the -u parameter if you have setup each account in ~/.cfcli.yml (see Readme.md), but that would require having a token for each account. This was setup before the multi account feature in cloudflare existed.
It looks like the zone create api supports passing in an account, but that is going to require some changes to support it
Daniel
