### ISSUE TITLE
Feature request - Logpush functionality

### ISSUE THREAD

**Issue by wingZero21** [danielpigott/cloudflare-cli#42]
Hi,

Is there any scope to look at adding logpush to be configured via the command line cli?

Cheers

Details:
https://support.cloudflare.com/hc/en-us/articles/360013599871-Getting-Started-with-Cloudflare-Logpush-Beta****

**Comment by danielpigott** [comment]
I don't think it is really feasible for me to look at this as it is an early access Enterprise feature and I don't have an Enterprise account (or really use cloudflare very much)
