### ISSUE TITLE
Push to Docker Hub

### ISSUE THREAD

**Issue by sweepyoface** [danielpigott/cloudflare-cli#49]
Hi, I'm working on a PR that adds a script to automatically run in Docker, similar to [Compose](https://github.com/docker/compose/blob/master/script/run/run.sh). It would be a lot easier if we could just have it pull from hub.docker.com instead of having to build the image. Is there any reason you've not done this?

**Comment by danielpigott** [comment]
I had set up a repo on Dockerhub @ https://hub.docker.com/r/dpig/cloudflare-cli
I guess I must have forgotten to update the docs.
I have also now set up my CircleCI config to automatically publish any changes on master to the 'latest' tag for that repo.
