### ISSUE TITLE
Support API Tokens

### ISSUE THREAD

**Issue by dannyockilson** [danielpigott/cloudflare-cli#50]
Cloudflare have launched API tokens for use with their API but the headers required to use it are different from the current implementation.

I've had a look and switching the headers would potentially require a BC break so wanted to get some input before putting in a PR.

Headers `X-Auth-Email` and `X-Auth-Key` (set here https://github.com/danielpigott/cloudflare-cli/blob/master/lib/apiClient.js#L14) are skipped and `Authorize: Bearer <token>` is used instead.

Should be fairly trivial to make both work; either by adding a new option to the cli wrapper or allowing email to be nullable (and assuming API token should be used if not set).

Let me know what you think and I'll put a PR in.

**Comment by danielpigott** [comment]
Definitely would be good to support this, though I would want to ensure it is backwards compatible.
I will take a look and update this issue with my suggestions.

**Comment by danielpigott** [comment]
What I am thinking is:
- add 2 new options
  - --api-token (option), apiToken (yml), CF_API_TOKEN (env var)
   - --api-key (option), apiKey (yml), CF_API_KEY (env var)
- deprecate the old --token (option), token (yaml) and remove in the next major release

Keen to hear your thougts.

**Comment by aequasi** [comment]
There is also the "org id"

**Comment by dannyockilson** [comment]
> What I am thinking is:
> 
> * add 2 new options
>   
>   * --api-token (option), apiToken (yml), CF_API_TOKEN (env var)
>   * --api-key (option), apiKey (yml), CF_API_KEY (env var)
> * deprecate the old --token (option), token (yaml) and remove in the next major release
> 
> Keen to hear your thougts.

Think that sounds like a clean way of handling it :) They sure got it through beta phase quickly so guess a move to that as the primary auth mechanism would be a good idea.

**Comment by dannyockilson** [comment]
Sorry been really busy the last few weeks will get back to you with a PR once I get a chance (hopefully in the next few weeks)

**Comment by darthwalsh** [comment]
I just hit the error message `The following required parameters were not provided: email` from a fresh npm install which doesn't have the latest master commits, but I did a git checkout and my API token is working great.

It looks like you could publish to npm with what you have now?

**Comment by danielpigott** [comment]
I have now published the changes as v4.0.0
