### ISSUE TITLE
Error response received: Invalid request headers

### ISSUE THREAD

**Issue by kevinkingdomviva** [danielpigott/cloudflare-cli#51]
Hi,

I have try API token and API keys
both of them can work ok according Cloudflare official test.
But when I want to add an A record
[centos@ip-172-26-7-72 ~]$ cfcli -a -t A add hkg 35.220.162.202
Error response received: Invalid request headers

I have always got the Error results above.
I can give you all the info include VPS login info and API key via Email or others.
Please help me.

**Comment by shep1987** [comment]
We are also seeing this...

**Comment by danielpigott** [comment]
Currently cfcli does not support the API token, it uses the API KEY method (https://api.cloudflare.com/#getting-started-requests).
I have tested running the example you provided and it worked for me.

Can you please do the following:
- Tell me which method you are using to set the credentials (.cfcli.yml, environment variables or options passed directly to the command)
- Try passing in your email and api key directly using the --email and --token options
- Confirm running the below command works as expected (returns a list of zones) with your credentials:
```
curl -X GET "https://api.cloudflare.com/client/v4/zones" \
     -H "Content-Type:application/json" \
     -H "X-Auth-Key:xxx" \
     -H "X-Auth-Email:example@example.com"
```

**Comment by kevinkingdomviva** [comment]
I have tried both Globlal API key and token key with .cfcli.yml form.

And,I have got the right messages from the following command.(using Global API key)
curl -X GET "https://api.cloudflare.com/client/v4/zones" \
     -H "Content-Type:application/json" \
     -H "X-Auth-Key:xxx" \part of them is ","is_subscribed":true,"can_subscribe":false,"legacy_id":"free","legacy_discount":false,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":15,"total_count":15},"success":true,"errors":[],"messages":[]}[centos@ip-172-26-7-72 ~]$ 
Still,I have got the wrong answer by Global API key,whether using .cfcli.yml or --email --tokencfcli -a -t A add hkg 35.220.162.202 --email kevinkingdomviva@gmail.com --token f3f3eedae29830   (token is not all of them)the results is:Error when communicating with api: Cannot read property 'id' of undefined



Kevin Luo

Purchase Engineer
Email: kevinkingdomviva@gmail.com
QQ: 3465141490
TKconsulting&accelerating software Co., Limited
 
From: Daniel Pigott
Date: 2019-08-31 09:11
To: danielpigott/cloudflare-cli
CC: kevinkingdomviva; Author
Subject: Re: [danielpigott/cloudflare-cli] Error response received: Invalid request headers (#51)
Currently cfcli does not support the API token, it uses the API KEY method (https://api.cloudflare.com/#getting-started-requests).
I have tested running the example you provided and it worked for me.
Can you please do the following:
Tell me which method you are using to set the credentials (.cfcli.yml, environment variables or options passed directly to the command)
Try passing in your email and api key directly using the --email and --token options
Confirm running the below command works as expected (returns a list of zones) with your credentials:
curl -X GET "https://api.cloudflare.com/client/v4/zones" \
     -H "Content-Type:application/json" \
     -H "X-Auth-Key:xxx" \
     -H "X-Auth-Email:example@example.com"

**Comment by danielpigott** [comment]
I can reproduce the error `Cannot read property 'id' of undefined` if I enter an invalid domain in the domain parameter of my cfcli.yml file. Can you please try passing in the --domain parameter and ensure that the domain parameter in your cfcli.yml file is correct

**Comment by shep1987** [comment]
Ours seemed to be a problem with how we were using env vars and escaping so we are ok.

Hopes yours gets fixed Kevin
