### ISSUE TITLE
errors on adding DNS A records,please help

### ISSUE THREAD

**Issue by kevinkingdomviva** [danielpigott/cloudflare-cli#54]
after install cloudflare-cli
I use
vi .cfcli.yml
to create
defaults:
    token: <in-RipHRCY6-VjWYwv>
    email: <kevinkingdomviva@gmail.com>
    domain: <doudoulong.club>
and save
but after I type
cfcli -a -t A add 3hk 1.1.1.1
The following required parameters were not provided: token,email
it shows the error above
I want to add a DNS A records to domain doudoulong.club so I type
cfcli -a -t A add 3hk 1.1.1.1 -e kevinkingdomviva@gmail.com -k f3f3eedae298
Error response received: DNS Validation Error
it shows the error above
how to fix it and add DNS records correctly?

Thanks very much for help~

**Comment by danielpigott** [comment]
Sorry for the delay in replying to this, I haven't been working on this project. Hopefully you managed to resolve this issue.  If not can you please try running the command
```
cfcli -a -t A add 3hk 1.1.1.1 -e kevinkingdomviva@gmail.com -k f3f3eedae298 -d doudoulong.club
```
And see if that works.

**Comment by kevinkingdomviva** [comment]
Great Thanks,it works!
but the created record at cloudflare are proxied

A
Auto
Proxied
Delete

A
2 min
DNS only
Delete

something like 1southkorea, I want the A record like 1sg , you can see it's DNS only.
But I don't find any option could do that,or I just can do it manully?

Good day~


Kevin Luo

Purchase Engineer
Email: kevinkingdomviva@gmail.com
QQ: 3465141490
TKconsulting&accelerating software Co., Limited
 
From: Daniel Pigott
Date: 2020-05-02 17:06
To: danielpigott/cloudflare-cli
CC: kevinkingdomviva; Author
Subject: Re: [danielpigott/cloudflare-cli] errors on adding DNS A records,please help (#54)
Sorry for the delay in replying to this, I haven't been working on this project. Hopefully you managed to resolve this issue. If not can you please try running the command
cfcli -a -t A add 3hk 1.1.1.1 -e kevinkingdomviva@gmail.com -k f3f3eedae298 -d doudoulong.club

And see if that works.

**Comment by danielpigott** [comment]
You can exclude the -a flag if you don't want cloudflare to proxy the created record
