### ISSUE TITLE
Error response received: Invalid request headers

### ISSUE THREAD

**Issue by edgarvenom** [danielpigott/cloudflare-cli#58]
I currently work with this api, I hope to add subdomains automatically to my cloudflare account.

I occupy centos 7, nginx

when I run or add my subdomain I get the error mentioned

[root@root ~]# cfcli -a -t A add my.dominio.com myipdestine
Error response received: Invalid request headers

**Comment by mwarkentin** [comment]
You're probably using one of the new cloudflare api tokens, it looks like this tool only supports the global keys right now: https://github.com/danielpigott/cloudflare-cli/issues/50

**Comment by danielpigott** [comment]
Version 4 has been updated to support API Tokens, please see if that resolves the issue

**Comment by JamieSinn** [comment]
Running `cfcli ls` also returns an error when using tokens. 
```
Error response received: Actor 'com.cloudflare.api.token.XXX' requires permission 'com.cloudflare.api.account.zone.read' to list zones
```
Yet, the `account.zone.read` permission is not possible to grant via the token system.

Event attempted to grant waaay more perms than needed to check whether or not this is working properly, and still not working.
https://i.imgur.com/mBNS4o0.png

**Comment by danielpigott** [comment]
I'm no expert on the api token system but this is what I have set up for my testing token

![Screen Shot 2020-10-02 at 12 29 09 am](https://user-images.githubusercontent.com/1411048/94822893-86c1c600-0446-11eb-8f87-b3cd7fb7e3dd.png)
