### ISSUE TITLE
[BUG!] Error response when adding numerical-only A records

### ISSUE THREAD

**Issue by pbdco** [danielpigott/cloudflare-cli#63]
Hi! When an A record name contains only numbers, this is the output:
`Error response received: Failed to parse request body, content-type must be application/json`

**Example:**
_cfcli -t A -l 1 add **123** 88.282.282.282_
`Error response received: Failed to parse request body, content-type must be application/json`

**Instead:**
_cfcli -t A -l 1 add **asd123** 88.282.282.282_
`Added A record asd123.example.com -> 88.282.282.282`

###### Using latest cloudflare-cli  -- Installed via npm (v. 12.18.2)

**Comment by danielpigott** [comment]
Thanks for this bug report, I have been able to reproduce the issue and will include a fix in the next update

**Comment by danielpigott** [comment]
This should be fixed now (version 4.1.0)
