### ISSUE TITLE
-h flag doesn't work as expected

### ISSUE THREAD

**Issue by offero** [danielpigott/cloudflare-cli#7]
Help does not show with the -h flag, while the CLI output states that it should be used.
```
$ cfcli -h
Use -h to display help

$ cfcli help
Command not found: help
NAME
    cfcli - Interact with cloudflare from the command line

SYNOPSIS
    cfcli [options] command [parameters]
...
```
cloudflare-cli@1.3.2
node v0.10.32
Mac OSX 10.10.2

**Comment by danielpigott** [comment]
Thanks for that, I have fixed this issue and published to npm (1.3.3)
