### ISSUE TITLE
Remove multiple records with same name

### ISSUE THREAD

**Issue by franciscopaniskaseker** [danielpigott/cloudflare-cli#8]
When you try to remove a specific name (record A) with multiple points (IPs), it will remove a randomly entry.

Example:
A mc 1.1.1.1
A mc 1.1.1.2
A mc 1.1.1.3
A mc 1.1.1.4

If you try to remove entry mc with 1.1.1.3 IP, it will not work. The command only work with name, not name and IP.

**Comment by danielpigott** [comment]
Hi Francisco,
I'll take a look at implementing this functionality.

**Comment by danielpigott** [comment]
I have updated cfcli with the following behaviour:
'cfcli removerecord mc' will remove all records with the name mc
'cfcli removerecord mc 1.1.1.1' will remove only the record with the name mc and value 1.1.1.1

It has been published to npm as version 1.4.0
