### ISSUE TITLE
when I try to remove all entries with same name

### ISSUE THREAD

**Issue by franciscopaniskaseker** [danielpigott/cloudflare-cli#9]
When I try to use "if /usr/bin/cfcli -c /root/cloudflare//cfcli.yml removerecord mc | egrep -i finished; then (...)" inside of a bash script I get:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)

When I use this command in terminal I get success. Do you know what is the problem?

**Comment by danielpigott** [comment]
Hi @franciscopaniskaseker sorry about the delay in responding to this.  This looks like an issue with process.stdout is being written to and when you are piping to grep the pipe gets closed before the stdout is finished. I am planning on rewriting a bunch of stuff in the tool so this won't be such an issue, but in the meantime I would suggest outputting all the output to a file and then subsequently grepping that file.
See https://www.npmjs.com/package/epipebomb for more info about the error.

**Comment by danielpigott** [comment]
This issue should be resolved with the version 2 release
